### ISSUE TITLE
BUG: User can click between filtering buttons

### ISSUE THREAD

**Issue by rachelktyjohnson** [rachelktyjohnson/hktbf22-student-contributors#18]
Users can currently click between the filter buttons and the result is an empty page of students.

**Comment by Lyndsayfutrell** [comment]
I feel like I should fix this one since it's my bug 😎 

Slack handle Lyndsay Futrell FSJS tech degree.

**Comment by rachelktyjohnson** [comment]
@Lyndsayfutrell all yours!
