### ISSUE TITLE
Add styles to visually differentiate between different TechDegrees

### ISSUE THREAD

**Issue by rachelktyjohnson** [rachelktyjohnson/hktbf22-student-contributors#4]
# Let's add some TechDegree colors

**You must be assigned this issue in order for your Pull Request to be accepted and merged. Please refer to "How to claim an Issue here: https://github.com/rachelktyjohnson/hktbf22-student-contributors/blob/master/CONTRIBUTING.md#how-to-claim-an-issue**

I think it'll be nice to be able to visually see what TechDegree everyone is in without reading too much. This issue requires you to write some CSS to add some sort of styles to each student card so it displays some sort of color based on what TechDegree the student is. 

Each `.student-card` will also have a class related to the TechDegree: `fewd`, `fsjs`, `web`, `python`, `data`, or `ux`. Use this class to dynamically add a background, a border, change the `a` color... anything that will help us quickly see which TechDegree a student is in! Here's an example:

![Issue 4 Example](https://i.imgur.com/iy5FQ8o.jpg)

Here are the different TechDegree colors:
```
Python & Data Analysis: #9f4b84;
UX: #4a4290;
FEWD: #3659a2;
FSJS and WEB: #0e8397;
```

**Comment by Eddayavuz** [comment]
Hi, just a suggestion it would've been useful to put a label like: "TechDegree Students Only"

**Comment by jajablinky** [comment]
i would like to be assigned this one please! geoff millar in slack!

**Comment by rachelktyjohnson** [comment]
@jajablinky all yours! Keen to see what you do
