### ISSUE TITLE
Randomize the order of student cards

### ISSUE THREAD

**Issue by rachelktyjohnson** [rachelktyjohnson/hktbf22-student-contributors#5]
# We're all equal here

**You must be assigned this issue in order for your Pull Request to be accepted and merged. Please refer to "How to claim an Issue here: https://github.com/rachelktyjohnson/hktbf22-student-contributors/blob/master/CONTRIBUTING.md#how-to-claim-an-issue**

We're all contributors here, so why should there be a set order to display everyone's card? This issue requires you to write some code that shuffles the order of students from `data.js` before appending data to the DOM. 

The original array in `data.js` must not be modified.

**Comment by TypeErrorDev** [comment]
Shall I attempt this? I think I shall 🙏

**Comment by rachelktyjohnson** [comment]
> Shall I attempt this? I think I shall 🙏 may I be assigned this issue please?

All yours!
