### ISSUE TITLE
Add "filter by TechDegree" function

### ISSUE THREAD

**Issue by rachelktyjohnson** [rachelktyjohnson/hktbf22-student-contributors#6]
# Let's see who's in what TechDegree

**You must be assigned this issue in order for your Pull Request to be accepted and merged. Please refer to "How to claim an Issue here: https://github.com/rachelktyjohnson/hktbf22-student-contributors/blob/master/CONTRIBUTING.md#how-to-claim-an-issue**

There are a few steps to this issue, so be prepared! The end goal is to to add 6 buttons, one for each TechDegree (FEWD, FSJS, WEB, PYTHON, DATA ANALYSIS, UX). There should also be a 7th "ALL" button that resets the filter. Clicking each one of these buttons should hide all students from different TechDegrees and only show those of the pressed TechDegree. 

The 2 main tasks here:
- Create the 7 buttons in HTML and then style them using CSS
- Write some Javascript code that allows users to interact with these buttons to show only students of that TechDegree

For example, clicking the "FSJS" button should hide all student cards but those who are in the Full Stack Javascript TechDegree.

**Comment by Lyndsayfutrell** [comment]
I would like to be assigned this Issue. My Slack handle is Lyndsay Futrell and I'm in the FSJS degree. Thank you!

**Comment by rachelktyjohnson** [comment]
> I would like to be assigned this Issue. My Slack handle is Lyndsay Futrell and I'm in the FSJS degree. Thank you!

All yours @Lyndsayfutrell!
